from . import project_project
from . import project_task
from . import coop_certificado
from . import coop_etapa
from . import coop_foja
from . import coop_pedido
from . import coop_corralon
from . import coop_acopio
from . import coop_orden_trabajo
from . import coop_relevamiento
from . import coop_presupuesto
from . import coop_herramienta
from . import coop_incidente
from . import coop_work_entry
