{
    'name': 'Cooperativa - Construcción',
    'version': '18.0.1.5.0',
    'summary': 'Obras, certificados de avance, proyección de pagos por etapa y plantel para cooperativas de construcción',
    'author': 'Coopeapp',
    'depends': ['coop_members', 'coop_payroll', 'project'],
    'data': [
        'security/ir.model.access.csv',
        'security/coop_construction_security.xml',
        'views/project_project_views.xml',
        'views/project_task_views.xml',
        'views/coop_certificado_views.xml',
        'views/coop_etapa_views.xml',
        'views/coop_foja_views.xml',
        'views/coop_pedido_views.xml',
        'views/coop_work_entry_views.xml',
        'views/coop_construction_menus.xml',
        'views/coop_corralon_views.xml',
    ],
    'license': 'LGPL-3',
    'installable': True,
    'application': False,
}
